wandb_version: 1

dropout:
  desc: null
  value: 0.05846804171050975
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 1.622432293530386e-05
weight_decay:
  desc: null
  value: 0.3
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688757669.571822
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.9
      5: 0.15.2
      6: 4.28.1
      8:
      - 1
      - 5
